import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

file = pd.read_csv('Clean_after.csv',low_memory=False)

file['Location'] = file['Location'].str.replace('uk','united kingdom')
file['Location'] = file['Location'].str.replace('united kingdom ','united kingdom')
file['Location'] = file['Location'].str.replace(' united kingdom','united kingdom')
file['Location'] = file['Location'].str.replace('great britain','united kingdom')
file['Location'] = file['Location'].str.replace('london ','london')
file['Location'] = file['Location'].str.replace('west london ','london')
file['Location'] = file['Location'].str.replace('city of london','london')
file['Location'] = file['Location'].str.replace('islington','london')
file['Location'] = file['Location'].str.replace('hackney','london')
file['Location'] = file['Location'].str.replace('london e14','london')
file['Location'] = file['Location'].str.replace('londone14','london')
file['Location'] = file['Location'].str.replace('london united kingdom','london')
file['Location'] = file['Location'].str.replace('londonunited kingdom','london')
file['Location'] = file['Location'].str.replace('london town','london')
file['Location'] = file['Location'].str.replace('west london','london')
file['Location'] = file['Location'].str.replace('noh west','north west')
file['Location'] = file['Location'].str.replace('noh east','north east')
file['Location'] = file['Location'].str.replace('noh wales','north wales')
file['Location'] = file['Location'].str.replace('noh yorkshire','north yorkshire')
file['Location'] = file['Location'].str.replace('greater manchester','manchester')
file['Location'] = file['Location'].str.replace('manchester ','manchester')
file['Location'] = file['Location'].str.replace('planet eah','eah')
file['Location'] = file['Location'].str.replace('nohern ireland','north ireland')
file['Location'] = file['Location'].str.replace('n ireland','north ireland')
file['Location'] = file['Location'].str.replace('usa','united states')
file['Location'] = file['Location'].str.replace('eu','europe')
file['Location'] = file['Location'].str.replace('europe ','europe')
file['Location'] = file['Location'].str.replace('europe ðŸ‡ªðŸ‡º','europe')
file['Location'] = file['Location'].str.replace('the europe','europe')
file['Location'] = file['Location'].str.replace('european union','europe')
file['Location'] = file['Location'].str.replace('europeropean union','europe')
file['Location'] = file['Location'].str.replace('europeropean union ','europe')
file['Location'] = file['Location'].str.replace('europeropean union ðŸ‡ªðŸ‡º','europe')
file['Location'] = file['Location'].str.replace('europerope ','europe')
file['Location'] = file['Location'].str.replace('europerope','europe')
file['Location'] = file['Location'].str.replace('nohumberlandunited kingdom','northumberland')
file['Location'] = file['Location'].str.replace('nohumberland','northumberland')
file['Location'] = file['Location'].str.replace('nohampton','northampton')
file['Location'] = file['Location'].str.replace('scotland ','scotland')
file['Location'] = file['Location'].str.replace('dublin city','dublin')
file['Location'] = file['Location'].str.replace(' Ã¼t','none')
file['Location'] = file['Location'].str.replace('everywhere','none')
file['Location'] = file['Location'].str.replace('here','none')
file['Location'] = file['Location'].str.replace('worldwide','none')
file['Location'] = file['Location'].str.replace('stockpo','stockport')
file['Location'] = file['Location'].str.replace('citizen of the world','none')
file['Location'] = file['Location'].str.replace('citizen of nownone','none')
file['Location'] = file['Location'].str.replace('global','none')
file['Location'] = file['Location'].str.replace('cornwall ','cornwall')
file['Location'] = file['Location'].str.replace('liverpoolunited kingdomðŸ‡¬ðŸ‡§ ','liverpool')
file['Location'] = file['Location'].str.replace('birminghamunited kingdom','birmingham')
file['Location'] = file['Location'].str.replace('norfolkunited kingdom','norfolk')
file['Location'] = file['Location'].str.replace('newpo','newport')
file['Location'] = file['Location'].str.replace('manchesterunited kingdom','manchester')
file['Location'] = file['Location'].str.replace('ðŸ‡¬ðŸ‡§','none')
file['Location'] = file['Location'].str.replace('an island in europe','none')
file['Location'] = file['Location'].str.replace('wrexham          anglesey','wrexham')
file['Location'] = file['Location'].str.replace('peh','none')
file['Location'] = file['Location'].str.replace('somewnone','none')
file['Location'] = file['Location'].str.replace('wohing','woking')
file['Location'] = file['Location'].str.replace('united kingdomin europe','united kingdom')
file['Location'] = file['Location'].str.replace('up noh','north england')
file['Location'] = file['Location'].str.replace('west yorkshireandalucia','west yorkshire')
file['Location'] = file['Location'].str.replace('west west sussex','west sussex')
file['Location'] = file['Location'].str.replace('newarkontrent','newark on trent')
file['Location'] = file['Location'].str.replace('the noh','north england')
file['Location'] = file['Location'].str.replace('up noh','north england')
file['Location'] = file['Location'].str.replace('stokeontrent','stoke on trent')
file['Location'] = file['Location'].str.replace('west west sussex','west sussex')
file['Location'] = file['Location'].str.replace('stocktonontees','stock on tees')
file['Location'] = file['Location'].str.replace('noh yorks','north york')
file['Location'] = file['Location'].str.replace('posmouth','portsmouth')
file['Location'] = file['Location'].str.replace('rickmanswoh','rickmansworth')
file['Location'] = file['Location'].str.replace('s e england','south east')
file['Location'] = file['Location'].str.replace('bonny scotland','bonny')
file['Location'] = file['Location'].str.replace('british migrant european','britain')
file['Location'] = file['Location'].str.replace('cambridgeuropenited kingdom','cambridge')
file['Location'] = file['Location'].str.replace('clotted cream first','none')
file['Location'] = file['Location'].str.replace('halepool','hartlepool')
file['Location'] = file['Location'].str.replace('iledefrance','france')
file['Location'] = file['Location'].str.replace('lnd','london')
file['Location'] = file['Location'].str.replace('liverpool ','liverpool')
file['Location'] = file['Location'].str.replace('deuropetschland','germany')
file['Location'] = file['Location'].str.replace('europe 🇪🇺','europe')
file['Location'] = file['Location'].str.replace('hefordshire','herefordshire')
file['Location'] = file['Location'].str.replace('noh carolina','north carolina')
file['Location'] = file['Location'].str.replace('noh london','north london')
file['Location'] = file['Location'].str.replace('south east','south east england ')
file['Location'] = file['Location'].str.replace('south west','south west england ')


file.to_csv('CleanLocation_after.csv')


location_count = file['Location'].value_counts()
location_count = location_count[1:30,]
plt.figure(figsize=(15,6))
sns.barplot(location_count.index,location_count.values,palette='Set2')
plt.title('Top 30 Location Cleaned')
plt.xlabel('Location')
plt.ylabel('Number of Locations')
plt.xticks(rotation=65)
plt.tight_layout()
#plt.show()

#file1 = file.groupby('Location')['Location'].value_counts().loc[lambda x: x>50]

#file1.to_csv('Location.csv')

